export default {
    GET_SELECTED_SEX: 'GET_SELECTED_SEX',
    GET_SEARCH_FIELD_VALUE: 'GET_SEARCH_FIELD_VALUE',
    LOGINED: 'LOGINED',
    GET_USER_DATA:  'GET_USER_DATA',
    LOGOUT: 'LOGOUT',
    IS_ADMIN: 'IS_ADMIN',
    GET_POST_DATA: 'GET_POST_DATA'
};
